### PR TITLE
Feature/add readme

### PR DESCRIPTION
**Pull request by dongminlee94**
## PR Description

This PR adds official `README`

## TODO

1. ~~Add README~~
2. Experiment new PEARL codes
3. Add early stopping condition #30 
4. Experiment new RL^2 codes using `num_sample_tasks`

### CODE REVIEW

**Comment by dongminlee94** [comment]
@all-contributors please add @dongminlee94 for code

**Comment by dongminlee94** [comment]
@all-contributors please add @Clyde21c for code

**Comment by dongminlee94** [comment]
@Clyde21c 승현님 최종 형태로 봐주시면 될 것 같습니다. 이것저것 테스트 하느라 쓸때없는 commit이 많았습니다..
https://github.com/dongminlee94/meta-rl/blob/feature/add_readme/README.md

**Comment by dongminlee94** [comment]
@all-contributors please add @dongminlee94 for doc

**Review by Clyde21c — APPROVED** [review]
Awesome! 👍

**Pull request merged**
